### ISSUE TITLE
Error installing on EndeavourOS kernel 5.17.9-arch1-1

### ISSUE THREAD

**Issue by edbizarro** [geminis3/envycontrol#45]
```
==> Starting package()...
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import envycontrol
  File "/home/edbizarro/.cache/yay/envycontrol/src/envycontrol/envycontrol.py", line 139
    TEARING_FIX = f'    Option "ForceCompositionPipeline" "true"\n'
                                                                  ^
SyntaxError: invalid syntax
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: envycontrol
```

Version 1.x was working fine.

**Comment by geminis3** [comment]
Hello there, what's your Python version?

**Comment by edbizarro** [comment]
Hi @geminis3, nevermind I have pyenv installed and set my global python to 2.7 (i don't know why), changing it back to 3.9 seems to "fix" de problem :)

**Comment by geminis3** [comment]
> Changing it back to 3.9 seems to "fix" de problem :)

I wrote the script for Python 3.X so that was to be expected ;)
